import fs from 'node:fs';import http from 'node:http';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import crypto from 'node:crypto';
const require=createRequire(process.env.PLAYWRIGHT_PACKAGE||import.meta.url);const {chromium}=require('playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const runtime=path.join(root,'runtime');fs.mkdirSync(runtime,{recursive:true});
const state=crypto.randomUUID();let callbacks=0,wrongRejected=0,headers=[];
const html=fs.readFileSync(path.join(root,'tests/flow.html'),'utf8').replace("location.href='appprivacy://callback?state='+encodeURIComponent(state||'')+'&code=mock-only';","location.href='/callback?state='+encodeURIComponent(state||'')+'&code=mock-only';");
const server=http.createServer((req,res)=>{res.setHeader('Cache-Control','no-store');const u=new URL(req.url,'http://localhost');headers.push((req.headers['accept-language']||'').startsWith('en-US'));if(u.pathname==='/callback'){if(u.searchParams.get('state')===state&&u.searchParams.get('code')==='mock-only'){callbacks++;res.end('mock_callback_accepted');}else{wrongRejected++;res.statusCode=403;res.end('mock_callback_rejected');}}else if(u.pathname==='/sw.js'){res.setHeader('Content-Type','application/javascript');res.end('');}else{res.setHeader('Content-Type','text/html');res.end(html);}});
await new Promise(r=>server.listen(18889,'127.0.0.1',r));const profiles=[];const results=[];
try{
 for(let i=0;i<2;i++){
  const dir=fs.mkdtempSync(path.join(runtime,'edge-empty-'));const context=await chromium.launchPersistentContext(dir,{executablePath:process.env.EDGE_EXECUTABLE||path.join(process.env['ProgramFiles(x86)']||'C:/Program Files (x86)','Microsoft/Edge/Application/msedge.exe'),headless:true,args:['--disable-extensions-except='+path.join(root,'edge'),'--load-extension='+path.join(root,'edge'),'--proxy-server=http://127.0.0.1:17992','--proxy-bypass-list=127.0.0.1;localhost','--host-resolver-rules=MAP * ~NOTFOUND, EXCLUDE 127.0.0.1, EXCLUDE localhost','--disable-background-networking','--disable-features=OptimizationHints,MediaRouter']});profiles.push(context);
  const page=await context.newPage();await page.goto('http://127.0.0.1:18889/authorize?state='+state);await page.waitForFunction(()=>!!window.fixtureResult);const result=await page.evaluate(()=>window.fixtureResult);
  await page.locator('#authorize').click();await page.waitForURL('**/callback?**');result.mock_callback_accepted=(await page.locator('body').innerText())==='mock_callback_accepted';
  await page.goto('http://127.0.0.1:18889/callback?state=wrong&code=mock-only');result.wrong_state_rejected=(await page.locator('body').innerText())==='mock_callback_rejected';
  result.passed=result.language==='en-US'&&result.timezone==='America/Los_Angeles'&&result.intl_constructor_timezone==='America/Los_Angeles'&&result.iframe_language==='en-US'&&result.iframe_timezone==='America/Los_Angeles'&&result.january_offset===480&&result.july_offset===420&&result.worker_blocked&&result.worker_constructor_blocked&&result.webrtc_blocked&&result.webrtc_constructor_blocked&&result.service_worker_blocked&&result.location_denied&&result.mock_callback_accepted&&result.wrong_state_rejected;
  results.push(result);
 }
 const report={scope:'Two empty Edge profiles; local synthetic browser redirect callback. OS custom scheme is tested separately. No account used.',profiles:results,callback_count:callbacks,wrong_state_rejected_count:wrongRejected,all_accept_language_us:headers.every(Boolean),real_account_used:false};
 fs.mkdirSync(path.join(root,'docs/evidence'),{recursive:true});fs.writeFileSync(path.join(root,'docs/evidence/desktop-browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(results.some(r=>!r.passed)||!report.all_accept_language_us)process.exitCode=1;
}finally{for(const p of profiles.reverse())await p.close().catch(()=>{});server.close();}
